# Generated by Django 4.0.4 on 2022-06-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deluxeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='placa',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
